<?php

namespace Database\Seeders\Evaluasi;

use App\Models\Evaluasi\PertanyaanEvaluasiUtama;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PertanyaanEvaluasiUtamaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $daftarEvaluasiUtama = [
            [
                'areaEvaluasiId' => 2,
                'daftarPertanyaan' => [
                    [
                        'nomor' => 1,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah pimpinan instansi/perusahaan anda secara prinsip dan resmi bertanggungjawab terhadap pelaksanaan program keamanan informasi (misal yang tercantum dalam ITSP), termasuk penetapan kebijakan terkait?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 2,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda memiliki fungsi atau bagian yang secara spesifik mempunyai tugas dan tanggungjawab mengelola keamanan informasi dan menjaga kepatuhannya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 3,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah pejabat/petugas pelaksana pengamanan informasi mempunyai wewenang yang sesuai untuk menerapkan dan menjamin kepatuhan program keamanan informasi?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 4,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah penanggungjawab pelaksanaan pengamanan informasi diberikan alokasi sumber daya yang sesuai untuk mengelola dan menjamin kepatuhan program keamanan informasi?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 5,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah peran pelaksana pengamanan informasi yang mencakup semua keperluan dipetakan dengan lengkap, termasuk kebutuhan audit internal dan persyaratan segregasi kewenangan?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 6,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah mendefinisikan persyaratan/standar kompetensi dan keahlian pelaksana pengelolaan keamanan informasi?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 7,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah semua pelaksana pengamanan informasi di instansi/perusahaan anda memiliki kompetensi dan keahlian yang memadai sesuai persyaratan/standar yang berlaku?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 8,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah menerapkan program sosialisasi dan peningkatan pemahaman untuk keamanan informasi, termasuk kepentingan kepatuhannya bagi semua pihak yang terkait?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 9,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda menerapkan program peningkatan kompetensi dan keahlian untuk pejabat dan petugas pelaksana pengelolaan keamanan informasi?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 10,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah mengintegrasikan keperluan/persyaratan keamanan informasi dalam proses kerja yang ada?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 11,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah mengidentifikasikan data pribadi yang digunakan dalam proses kerja dan menerapkan pengamanan sesuai dengan peraturan perundangan yang berlaku?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 12,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah tanggungjawab pengelolaan keamanan informasi mencakup koordinasi dengan pihak pengelola/pengguna aset informasi internal dan eksternal maupun pihak lain yang berkepentingan, untuk mengidentifikasikan persyaratan/kebutuhan pengamanan (misal: pertukaran informasi atau kerjasama yang melibatkan informasi penting) dan menyelesaikan permasalahan yang ada?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 13,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah pengelola keamanan informasi secara proaktif berkoordinasi dengan satker terkait (SDM, Legal/Hukum, Umum, Keuangan dll) dan pihak eksternal yang berkepentingan (misal: regulator, aparat keamanan) untuk menerapkan dan menjamin kepatuhan pengamanan informasi terkait proses kerja yang melibatkan berbagai pihak?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 14,
                        'tingkat_kematangan' => 'III',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah tanggungjawab untuk memutuskan, merancang, melaksanakan dan mengelola langkah kelangsungan layanan TIK (business continuity dan disaster recovery plans) sudah didefinisikan dan dialokasikan?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 15,
                        'tingkat_kematangan' => 'III',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah penanggungjawab pengelolaan keamanan informasi melaporkan kondisi, kinerja/efektifitas dan kepatuhan program keamanan informasi kepada pimpinan instansi/perusahaan secara rutin dan resmi?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 16,
                        'tingkat_kematangan' => 'III',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah kondisi dan permasalahan keamanan informasi di instansi/perusahaan anda menjadi konsiderans atau bagian dari proses pengambilan keputusan strategis di instansi/perusahaan anda?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 17,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah pimpinan satuan kerja di instansi/perusahaan anda menerapkan program khusus untuk mematuhi tujuan dan sasaran kepatuhan pengamanan informasi, khususnya yang mencakup aset informasi yang menjadi tanggungjawabnya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                    [
                        'nomor' => 18,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah mendefinisikan metrik, paramater dan proses pengukuran kinerja pengelolaan keamanan informasi yang mencakup mekanisme, waktu pengukuran, pelaksananya, pemantauannya dan eskalasi pelaporannya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                    [
                        'nomor' => 19,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah menerapkan program penilaian kinerja pengelolaan keamanan informasi bagi individu (pejabat & petugas) pelaksananya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                    [
                        'nomor' => 20,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah menerapkan target dan sasaran pengelolaan keamanan informasi untuk berbagai area yang relevan, mengevaluasi pencapaiannya secara rutin, menerapkan langkah perbaikan untuk mencapai sasaran yang ada, termasuk pelaporan statusnya kepada pimpinan instansi/perusahaan?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                    [
                        'nomor' => 21,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah mengidentifikasi legislasi, perangkat hukum dan standar lainnya terkait keamanan informasi yang harus dipatuhi dan menganalisa tingkat kepatuhannya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                    [
                        'nomor' => 22,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah mendefinisikan kebijakan dan langkah penanggulangan insiden keamanan informasi yang menyangkut pelanggaran hukum (pidana dan perdata)?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                ],
            ],
            [
                'areaEvaluasiId' => 3,
                'daftarPertanyaan' => [
                    [
                        'nomor' => 1,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda mempunyai program kerja pengelolaan risiko keamanan informasi yang terdokumentasi dan secara resmi digunakan?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 2,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah menetapkan penanggung jawab manajemen risiko dan eskalasi pelaporan status pengelolaan risiko keamanan informasi sampai ke tingkat pimpinan?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 3,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda mempunyai kerangka kerja pengelolaan risiko keamanan informasi yang terdokumentasi dan secara resmi digunakan?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 4,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah kerangka kerja pengelolaan risiko ini mencakup definisi dan hubungan tingkat klasifikasi aset informasi, tingkat ancaman, kemungkinan terjadinya ancaman dan dampak kerugian terhadap instansi/perusahaan anda?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 5,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah menetapkan ambang batas tingkat risiko yang dapat diterima?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 6,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah mendefinisikan kepemilikan dan pihak pengelola (custodian) aset informasi yang ada, termasuk aset utama/penting dan proses kerja utama yang menggunakan aset tersebut?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 7,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah ancaman dan kelemahan yang terkait dengan aset informasi, terutama untuk setiap aset utama sudah teridentifikasi?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 8,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah dampak kerugian yang terkait dengan hilangnya/terganggunya fungsi aset utama sudah ditetapkan sesuai dengan definisi yang ada?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 9,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah menjalankan inisiatif analisa/kajian risiko keamanan informasi secara terstruktur terhadap aset informasi yang ada (untuk nantinya digunakan dalam mengidentifikasi langkah mitigasi atau penanggulangan yang menjadi bagian dari program pengelolaan keamanan informasi)?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 10,
                        'tingkat_kematangan' => 'II',
                        'pertanyaan_tahap' => 1,
                        'pertanyaan' => 'Apakah instansi/perusahaan anda sudah menyusun langkah mitigasi dan penanggulangan risiko yang ada?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan',
                        'status_ketiga' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_keempat' => 'Diterapkan Secara Menyeluruh',
                        'skor_pertama' => 0,
                        'skor_kedua' => 1,
                        'skor_ketiga' => 2,
                        'skor_keempat' => 3,
                    ],
                    [
                        'nomor' => 11,
                        'tingkat_kematangan' => 'III',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah langkah mitigasi risiko disusun sesuai tingkat prioritas dengan target penyelesaiannya dan penanggungjawabnya, dengan memastikan efektivitas penggunaan sumber daya yang dapat menurunkan tingkat risiko ke ambang batas yang bisa diterima dengan meminimalisir dampak terhadap operasional layanan TIK?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_ketiga' => 'Diterapkan Secara Menyeluruh',
                        'status_keempat' => 'Diterapkan Secara Efektif dan Terukur',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 12,
                        'tingkat_kematangan' => 'III',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah status penyelesaian langkah mitigasi risiko dipantau secara berkala, untuk memastikan penyelesaian atau kemajuan kerjanya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_ketiga' => 'Diterapkan Secara Menyeluruh',
                        'status_keempat' => 'Diterapkan Secara Efektif dan Terukur',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 13,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah penyelesaian langkah mitigasi yang sudah diterapkan dievaluasi, melalui proses yang obyektif/terukur untuk memastikan konsistensi dan efektivitasnya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_ketiga' => 'Diterapkan Secara Menyeluruh',
                        'status_keempat' => 'Diterapkan Secara Efektif dan Terukur',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 14,
                        'tingkat_kematangan' => 'IV',
                        'pertanyaan_tahap' => 2,
                        'pertanyaan' => 'Apakah profil risiko berikut bentuk mitigasinya secara berkala dikaji ulang untuk memastikan akurasi dan validitasnya, termasuk merevisi profil apabila ada perubahan kondisi yang signifikan atau keperluan penerapan bentuk pengamanan baru?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_ketiga' => 'Diterapkan Secara Menyeluruh',
                        'status_keempat' => 'Diterapkan Secara Efektif dan Terukur',
                        'skor_pertama' => 0,
                        'skor_kedua' => 2,
                        'skor_ketiga' => 4,
                        'skor_keempat' => 6,
                    ],
                    [
                        'nomor' => 15,
                        'tingkat_kematangan' => 'V',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah kerangka kerja pengelolaan risiko secara berkala dikaji untuk memastikan/meningkatkan efektivitasnya?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_ketiga' => 'Diterapkan Secara Menyeluruh',
                        'status_keempat' => 'Diterapkan Secara Efektif dan Terukur',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                    [
                        'nomor' => 16,
                        'tingkat_kematangan' => 'V',
                        'pertanyaan_tahap' => 3,
                        'pertanyaan' => 'Apakah pengelolaan risiko menjadi bagian dari kriteria proses penilaian obyektif kinerja efektivitas pengamanan?',
                        'status_pertama' => 'Tidak Dilakukan',
                        'status_kedua' => 'Dalam Perencanaan / Diterapkan Sebagian',
                        'status_ketiga' => 'Diterapkan Secara Menyeluruh',
                        'status_keempat' => 'Diterapkan Secara Efektif dan Terukur',
                        'skor_pertama' => 0,
                        'skor_kedua' => 3,
                        'skor_ketiga' => 6,
                        'skor_keempat' => 9,
                    ],
                ],
            ]

        ];


        foreach ($daftarEvaluasiUtama as $evaluasiUtama) {
            $areaEvaluasiId = $evaluasiUtama['areaEvaluasiId'];
            foreach ($evaluasiUtama['daftarPertanyaan'] as $pertanyaan) {
                PertanyaanEvaluasiUtama::create([
                    'area_evaluasi_id' => $areaEvaluasiId,
                    'nomor' => $pertanyaan['nomor'],
                    'tingkat_kematangan' => $pertanyaan['tingkat_kematangan'],
                    'pertanyaan_tahap' => $pertanyaan['pertanyaan_tahap'],
                    'pertanyaan' => $pertanyaan['pertanyaan'],
                    'status_pertama' => $pertanyaan['status_pertama'],
                    'status_kedua' => $pertanyaan['status_kedua'],
                    'status_ketiga' => $pertanyaan['status_ketiga'],
                    'status_keempat' => $pertanyaan['status_keempat'],
                    'skor_status_pertama' => $pertanyaan['skor_pertama'],
                    'skor_status_kedua' => $pertanyaan['skor_kedua'],
                    'skor_status_ketiga' => $pertanyaan['skor_ketiga'],
                    'skor_status_keempat' => $pertanyaan['skor_keempat'],
                ]);
            }
        }
    }
}
